name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-sdk-version: 29
        
    - name: make gradlew executable
      run: chmod +x gradlew

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run tests
        run: ./gradlew test
  
