name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
        
      - name: lint
        run: ./gradlew ktlint 

      - name: code quality with deteckt
        run: ./gradlw deteckt

      - name: test
        run: ./gradlw test   
  
