name: Android CI

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Prepare
        uses: MahmoudMabrok/QuranyApp/.github/workflows/prepare.yml@main
     
     - name: Run tests
        run: ./gradlew test
