name: Detekt

on: 
  push:
    paths:
      - '**/*.kt'
  pull_request_target:
    paths:
      - '**/*.kt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v3

    - name: Setup detekt
      uses: peter-murray/setup-detekt@v2
      with:
          detekt_version: v1.22.0

    - name: Run Detekt
      continue-on-error: true
      run: | 
        detekt-cli --base-path . \
                   --input ${{ github.workspace }} \
                   --report md:${{ github.workspace }}/detekt.md
