name: Prepare

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      hasP: contains(github.event_name, 'push') 
    
    steps:
    - name: print
      run: echo "$hasP"
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-sdk-version: 29
        
    - name: make gradlew executable
      run: chmod +x gradlew
  
