name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
  
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-sdk-version: 34
          
      - name: make gradlew executable
        run: chmod +x gradlew
        
      - name: BUild
        run: ./gradlew build 
  
